[project]
name = "Orca-IDE"
version = "0.1.0"
description = ""
main_script = "./src/main.py"

[packages]
PyQt5 = "5.15.10"
QScintilla = "2.14.1"

[scripts]
upgrade-pip = "python -m pip install --upgrade pip"
